%
\photosymbol{Ableton-Dark} & Ableton Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Ableton-Light} & Ableton Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{acrobat} & acrobat & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ActivityPub-Dark} & ActivityPub Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{ActivityPub-Light} & ActivityPub Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Actix-Dark} & Actix Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Actix-Light} & Actix Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{adobespark} & adobespark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Adonis} & Adonis & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{aero} & aero & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{AfterEffects} & AfterEffects & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AI} & AI & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AiScript-Dark} & AiScript Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AiScript-Light} & AiScript Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{alacritty-dark} & alacritty dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{alacritty-light} & alacritty light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{alchemy-dark} & alchemy dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{alchemy-light} & alchemy light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AlpineJS-Dark} & AlpineJS Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AlpineJS-Light} & AlpineJS Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Anaconda-Dark} & Anaconda Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Anaconda-Light} & Anaconda Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{android-dark} & android dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{android-light} & android light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AndroidStudio-Dark} & AndroidStudio Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AndroidStudio-Light} & AndroidStudio Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Angular-Dark} & Angular Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Angular-Light} & Angular Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{animate} & animate & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Ansible} & Ansible & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{anss-dark} & anss dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{anss-light} & anss light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{api-dark} & api dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{api-light} & api light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{apidog-dark} & apidog dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{apidog-light} & apidog light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Apollo} & Apollo & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{appcode-dark} & appcode dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{appcode-light} & appcode light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Apple-Dark} & Apple Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Apple-Light} & Apple Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AppleMetal} & AppleMetal & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Appwrite} & Appwrite & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{aqua-dark} & aqua dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{aqua-light} & aqua light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{arcbrowser-dark} & arcbrowser dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{arcbrowser-light} & arcbrowser light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Arch-Dark} & Arch Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Arch-Light} & Arch Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Arduino} & Arduino & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{argocd-dark} & argocd dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{argocd-light} & argocd light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{assembly} & assembly & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Astro} & Astro & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Atom} & Atom & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Audition} & Audition & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{authjs-dark} & authjs dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{authjs-light} & authjs light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{autocad-dark} & autocad dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AutoCAD-Light} & AutoCAD Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{avaloniaui} & avaloniaui & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AWS-Dark} & AWS Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{AWS-Light} & AWS Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Azul} & Azul & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Azure-Dark} & Azure Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Azure-Light} & Azure Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{azuredevops-dark} & azuredevops dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{azuredevops-light} & azuredevops light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Babel} & Babel & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{barbajs} & barbajs & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Bash-Dark} & Bash Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Bash-Light} & Bash Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{beeceptor-dark} & beeceptor dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{beeceptor-light} & beeceptor light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{behance} & behance & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{behat-dark} & behat dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{behat-light} & behat light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Bevy-Dark} & Bevy Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Bevy-Light} & Bevy Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{bigquery-dark} & bigquery dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{bigquery-light} & bigquery light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{BitBucket-Dark} & BitBucket Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{BitBucket-Light} & BitBucket Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{blazor-dark} & blazor dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{blazor-light} & blazor light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Blender-Dark} & Blender Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Blender-Light} & Blender Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{bluesky-dark} & bluesky dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{bluesky-light} & bluesky light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{bokeh-dark} & bokeh dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{bokeh-light} & bokeh light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Bootstrap} & Bootstrap & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{brave-dark} & brave dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{brave-light} & brave light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{breeze} & breeze & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{bridge} & bridge & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{BSD-Dark} & BSD Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{BSD-Light} & BSD Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{btlo-dark} & btlo dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{btlo-light} & btlo light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{bulma-dark} & bulma dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{bulma-light} & bulma light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Bun-Dark} & Bun Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Bun-Light} & Bun Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{C} & C & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{cachyos-dark} & cachyos dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{cachyos-light} & cachyos light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{caddy-dark} & caddy dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{caddy-light} & caddy light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Caffe} & Caffe & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{cairo-dark} & cairo dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{cairo-light} & cairo light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{canva-dark} & canva dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{canva-light} & canva light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{capacitor-dark} & capacitor dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{capacitor-light} & capacitor light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{capture} & capture & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{cashier} & cashier & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Cassandra-Dark} & Cassandra Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Cassandra-Light} & Cassandra Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{characteranimator} & characteranimator & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{chartjs-dark} & chartjs dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{chartjs-light} & chartjs light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{chatgpt-dark} & chatgpt dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{chatgpt-light} & chatgpt light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{chrome-dark} & chrome dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{chrome-light} & chrome light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{chromium-dark} & chromium dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{chromium-light} & chromium light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{circleci-dark} & circleci dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{circleci-light} & circleci light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{claude-dark} & claude dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{claude-light} & claude light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{clerk} & clerk & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CLion-Dark} & CLion Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CLion-Light} & CLion Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Clojure-Dark} & Clojure Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Clojure-Light} & Clojure Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Cloudflare-Dark} & Cloudflare Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Cloudflare-Light} & Cloudflare Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CMake-Dark} & CMake Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CMake-Light} & CMake Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{cockroachdb-dark} & cockroachdb dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{cockroachdb-light} & cockroachdb light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{codeberg-dark} & codeberg dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{codeberg-light} & codeberg light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{codeigniter-dark} & codeigniter dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{codeigniter-light} & codeigniter light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CodePen-Dark} & CodePen Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CodePen-Light} & CodePen Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CoffeeScript-Dark} & CoffeeScript Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CoffeeScript-Light} & CoffeeScript Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{commercetools-dark} & commercetools dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{commercetools-light} & commercetools light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{composer-dark} & composer dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{composer-light} & composer light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{contentful-dark} & contentful dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{contentful-light} & contentful light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CPP} & CPP & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{creativecloud} & creativecloud & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Crystal-Dark} & Crystal Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Crystal-Light} & Crystal Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CS} & CS & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CSharp} & CSharp & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{CSS} & CSS & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{cuda-dark} & cuda dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{cuda-light} & cuda light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Cypress-Dark} & Cypress Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Cypress-Light} & Cypress Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{d} & d & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{D3-Dark} & D3 Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{D3-Light} & D3 Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{dailydev-dark} & dailydev dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{dailydev-light} & dailydev light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{daisyui-dark} & daisyui dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{daisyui-light} & daisyui light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Dart-Dark} & Dart Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Dart-Light} & Dart Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{databricks-dark} & databricks dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{databricks-light} & databricks light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{datadog} & datadog & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{datagrip-dark} & datagrip dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{datagrip-light} & datagrip light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{dataspell-dark} & dataspell dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{dataspell-light} & dataspell light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{davinci} & davinci & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{dbeaver-dark} & dbeaver dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{dbeaver-light} & dbeaver light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Debian-Dark} & Debian Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Debian-Light} & Debian Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{debian} & debian & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{defold-dark} & defold dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{defold-light} & defold light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{DENO-Dark} & DENO Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{DENO-Light} & DENO Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{desmos} & desmos & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{DevTo-Dark} & DevTo Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{DevTo-Light} & DevTo Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{digitalocean-dark} & digitalocean dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{digitalocean-light} & digitalocean light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{dimension} & dimension & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{directus} & directus & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Discord} & Discord & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{DiscordBots} & DiscordBots & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{DiscordJS-Dark} & DiscordJS Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{DiscordJS-Light} & DiscordJS Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Django} & Django & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Docker} & Docker & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{docksal-dark} & docksal dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{docksal-light} & docksal light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{docsify-dark} & docsify dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{docsify-light} & docsify light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{DotNet} & DotNet & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{dreamweaver} & dreamweaver & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{drupal-dark} & drupal dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{drupal-light} & drupal light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{duckduckgo} & duckduckgo & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{dusk} & dusk & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{DynamoDB-Dark} & DynamoDB Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{DynamoDB-Light} & DynamoDB Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{echo} & echo & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Eclipse-Dark} & Eclipse Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Eclipse-Light} & Eclipse Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{edge-dark} & edge dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{edge-light} & edge light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Elasticsearch-Dark} & Elasticsearch Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Elasticsearch-Light} & Elasticsearch Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Electron} & Electron & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{elementplus-dark} & elementplus dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{elementplus-light} & elementplus light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Elixir-Dark} & Elixir Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Elixir-Light} & Elixir Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{elm-dark} & elm dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{elm-light} & elm light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Elysia-Dark} & Elysia Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Elysia-Light} & Elysia Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Emacs} & Emacs & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Embedded} & Embedded & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Ember} & Ember & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Emotion-Dark} & Emotion Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Emotion-Light} & Emotion Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{envoyer} & envoyer & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{erlang-dark} & erlang dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{erlang-light} & erlang light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{etcd-dark} & etcd dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{etcd-light} & etcd light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{excel-dark} & excel dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{excel-light} & excel light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{expo-dark} & expo dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{expo-light} & expo light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ExpressJS-Dark} & ExpressJS Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{ExpressJS-Light} & ExpressJS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{fabric-dark} & fabric dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{fabric-light} & fabric light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{facebook} & facebook & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fastai-dark} & fastai dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fastai-light} & fastai light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{FastAPI} & FastAPI & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fastlane-dark} & fastlane dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fastlane-light} & fastlane light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Fediverse-Dark} & Fediverse Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Fediverse-Light} & Fediverse Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ffmpeg-dark} & ffmpeg dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ffmpeg-light} & ffmpeg light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{fiber-dark} & fiber dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{fiber-light} & fiber light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Figma-Dark} & Figma Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Figma-Light} & Figma Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{filament} & filament & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Firebase-Dark} & Firebase Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Firebase-Light} & Firebase Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{firefox-dark} & firefox dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{firefox-light} & firefox light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{flameshot} & flameshot & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Flask-Dark} & Flask Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Flask-Light} & Flask Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fleet-dark} & fleet dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fleet-light} & fleet light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Flutter-Dark} & Flutter Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Flutter-Light} & Flutter Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{flutterflow-dark} & flutterflow dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{flutterflow-light} & flutterflow light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{flyio} & flyio & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fonts} & fonts & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{forge} & forge & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{forgejo-dark} & forgejo dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{forgejo-light} & forgejo light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Forth} & Forth & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Fortran} & Fortran & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{FPGA} & FPGA & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{frankenphp-dark} & frankenphp dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{frankenphp-light} & frankenphp light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fresco} & fresco & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fresh-dark} & fresh dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fresh-light} & fresh light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{fuse} & fuse & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{GameMakerStudio} & GameMakerStudio & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ganache-dark} & ganache dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ganache-light} & ganache light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Gatsby} & Gatsby & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GCP-Dark} & GCP Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{GCP-Light} & GCP Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gdevelop-dark} & gdevelop dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gdevelop-light} & gdevelop light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gemini-dark} & gemini dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gemini-light} & gemini light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{gentoo-dark} & gentoo dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{gentoo-light} & gentoo light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Gherkin-Dark} & Gherkin Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Gherkin-Light} & Gherkin Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gimp-dark} & gimp dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gimp-light} & gimp light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{git-dark} & git dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{git-light} & git light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Git} & Git & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gitea-dark} & gitea dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gitea-light} & gitea light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Github-Dark} & Github Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Github-Light} & Github Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GithubActions-Dark} & GithubActions Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{GithubActions-Light} & GithubActions Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{githubcopilot-dark} & githubcopilot dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{githubcopilot-light} & githubcopilot light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{githubpages-dark} & githubpages dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{githubpages-light} & githubpages light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gitkraken-dark} & gitkraken dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gitkraken-light} & gitkraken light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GitLab-Dark} & GitLab Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GitLab-Light} & GitLab Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gleam-dark} & gleam dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gleam-light} & gleam light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Gmail-Dark} & Gmail Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Gmail-Light} & Gmail Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gnome-dark} & gnome dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gnome-light} & gnome light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{GnuMake} & GnuMake & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Godot-Dark} & Godot Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Godot-Light} & Godot Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{goland-dark} & goland dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{goland-light} & goland light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GoLang} & GoLang & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{googleanalytics-dark} & googleanalytics dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{googleanalytics-light} & googleanalytics light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{googleappsscript-dark} & googleappsscript dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{googleappsscript-light} & googleappsscript light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Gradle-Dark} & Gradle Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Gradle-Light} & Gradle Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Grafana-Dark} & Grafana Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Grafana-Light} & Grafana Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{grails} & grails & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GraphQL-Dark} & GraphQL Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GraphQL-Light} & GraphQL Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gromacs-dark} & gromacs dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{gromacs-light} & gromacs light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{grpc-dark} & grpc dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{grpc-light} & grpc light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{grunt-dark} & grunt dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{grunt-light} & grunt light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gsap-dark} & gsap dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{gsap-light} & gsap light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{GTK-Dark} & GTK Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{GTK-Light} & GTK Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Gulp} & Gulp & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hadoop-dark} & hadoop dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{hadoop-light} & hadoop light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{HappyMac} & HappyMac & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hardhat-dark} & hardhat dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hardhat-light} & hardhat light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Haskell-Dark} & Haskell Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Haskell-Light} & Haskell Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Haxe-Dark} & Haxe Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Haxe-Light} & Haxe Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{HaxeFlixel-Dark} & HaxeFlixel Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{HaxeFlixel-Light} & HaxeFlixel Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{helix-dark} & helix dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{helix-light} & helix light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{helm-dark} & helm dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{helm-light} & helm light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{herd} & herd & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Heroku} & Heroku & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Hibernate-Dark} & Hibernate Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Hibernate-Light} & Hibernate Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{holyc} & holyc & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hono-dark} & hono dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hono-light} & hono light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{horizon} & horizon & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{HTML} & HTML & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Htmx-Dark} & Htmx Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Htmx-Light} & Htmx Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{htop-dark} & htop dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{htop-light} & htop light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{huggingface-dark} & huggingface dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{huggingface-light} & huggingface light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hugo-dark} & hugo dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hugo-light} & hugo light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{hydrogen-dark} & hydrogen dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hydrogen-light} & hydrogen light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{hyprland-dark} & hyprland dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{hyprland-light} & hyprland light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{i3-dark} & i3 dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{i3-light} & i3 light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{iced} & iced & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Idea-Dark} & Idea Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Idea-Light} & Idea Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ignite-dark} & ignite dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ignite-light} & ignite light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Illustrator} & Illustrator & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{incopy} & incopy & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{indesign} & indesign & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{inertia} & inertia & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{infura} & infura & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{inkscape-dark} & inkscape dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{inkscape-light} & inkscape light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{insomnia} & insomnia & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Instagram} & Instagram & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{integrations-dark} & integrations dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{integrations-light} & integrations light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{IPFS-Dark} & IPFS Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{IPFS-Light} & IPFS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{jamovi} & jamovi & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Java-Dark} & Java Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Java-Light} & Java Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{JavaScript} & JavaScript & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{jax-dark} & jax dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{jax-light} & jax light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{jekyll-dark} & jekyll dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{jekyll-light} & jekyll light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Jenkins-Dark} & Jenkins Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Jenkins-Light} & Jenkins Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Jest} & Jest & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{jetpackcompose-dark} & jetpackcompose dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{jetpackcompose-light} & jetpackcompose light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{jetstream} & jetstream & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{jira-dark} & jira dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{jira-light} & jira light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{joomla-dark} & joomla dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{joomla-light} & joomla light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{JQuery} & JQuery & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Julia-Dark} & Julia Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Julia-Light} & Julia Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{jupyter-dark} & jupyter dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{jupyter-light} & jupyter light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Kafka} & Kafka & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kaggle-dark} & kaggle dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kaggle-light} & kaggle light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kakoune-dark} & kakoune dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kakoune-light} & kakoune light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Kali-Dark} & Kali Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Kali-Light} & Kali Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{karma-dark} & karma dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{karma-light} & karma light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kde-dark} & kde dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{kde-light} & kde light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{keycloak} & keycloak & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{keydb-dark} & keydb dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{keydb-light} & keydb light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kibana-dark} & kibana dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{kibana-light} & kibana light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kitty-dark} & kitty dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{kitty-light} & kitty light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Kotlin-Dark} & Kotlin Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Kotlin-Light} & Kotlin Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Ktor-Dark} & Ktor Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Ktor-Light} & Ktor Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Kubernetes} & Kubernetes & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{langchain-dark} & langchain dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{langchain-light} & langchain light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Laravel-Dark} & Laravel Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Laravel-Light} & Laravel Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{laravelspark-dark} & laravelspark dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{laravelspark-light} & laravelspark light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{LaTeX-Dark} & LaTeX Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{LaTeX-Light} & LaTeX Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{leaflet-dark} & leaflet dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{leaflet-light} & leaflet light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{leetcode-dark} & leetcode dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{leetcode-light} & leetcode light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Less-Dark} & Less Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Less-Light} & Less Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{libsql} & libsql & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lighthouse} & lighthouse & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lightning-dark} & lightning dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lightning-light} & lightning light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lightroom} & lightroom & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lightroomclassic} & lightroomclassic & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{LinkedIn} & LinkedIn & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Linux-Dark} & Linux Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Linux-Light} & Linux Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Lit-Dark} & Lit Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Lit-Light} & Lit Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{litmus-dark} & litmus dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{litmus-light} & litmus light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{livewire-dark} & livewire dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{livewire-light} & livewire light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{llamaindex-dark} & llamaindex dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{llamaindex-light} & llamaindex light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{logto-dark} & logto dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{logto-light} & logto light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{looker-dark} & looker dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{looker-light} & looker light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Lua-Dark} & Lua Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Lua-Light} & Lua Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{luau} & luau & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lucidchart-dark} & lucidchart dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{lucidchart-light} & lucidchart light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lunacy} & lunacy & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lxc-dark} & lxc dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{lxc-light} & lxc light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{manjaro} & manjaro & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mariadb-dark} & mariadb dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mariadb-light} & mariadb light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Markdown-Dark} & Markdown Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Markdown-Light} & Markdown Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Mastodon-Dark} & Mastodon Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Mastodon-Light} & Mastodon Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{MaterialUI-Dark} & MaterialUI Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{MaterialUI-Light} & MaterialUI Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Matlab-Dark} & Matlab Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Matlab-Light} & Matlab Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{matplotlib-dark} & matplotlib dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{matplotlib-light} & matplotlib light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Maven-Dark} & Maven Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Maven-Light} & Maven Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mediaencoder} & mediaencoder & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{mermaid} & mermaid & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{metabase-dark} & metabase dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{metabase-light} & metabase light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{meteorjs-dark} & meteorjs dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{meteorjs-light} & meteorjs light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{microsoftcopilot-dark} & microsoftcopilot dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{microsoftcopilot-light} & microsoftcopilot light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{millionjs-dark} & millionjs dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{millionjs-light} & millionjs light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{milvus-dark} & milvus dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{milvus-light} & milvus light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mindsdb-dark} & mindsdb dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mindsdb-light} & mindsdb light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Mint-Dark} & Mint Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Mint-Light} & Mint Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{miro} & miro & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Misskey-Dark} & Misskey Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Misskey-Light} & Misskey Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mistral-dark} & mistral dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mistral-light} & mistral light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{mjml-dark} & mjml dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mjml-light} & mjml light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ml5-dark} & ml5 dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ml5-light} & ml5 light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mocha-dark} & mocha dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mocha-light} & mocha light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mojo-dark} & mojo dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mojo-light} & mojo light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{MongoDB} & MongoDB & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{mongoose} & mongoose & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{MySQL-Dark} & MySQL Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{MySQL-Light} & MySQL Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NeoVim-Dark} & NeoVim Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NeoVim-Light} & NeoVim Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NestJS-Dark} & NestJS Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NestJS-Light} & NestJS Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Netlify-Dark} & Netlify Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Netlify-Light} & Netlify Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{NextJS-Dark} & NextJS Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NextJS-Light} & NextJS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Nginx} & Nginx & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ngrok} & ngrok & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Nim-Dark} & Nim Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Nim-Light} & Nim Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Nix-Dark} & Nix Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Nix-Light} & Nix Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{nixos-dark} & nixos dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{nixos-light} & nixos light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{NodeJS-Dark} & NodeJS Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NodeJS-Light} & NodeJS Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{notepadpp-dark} & notepadpp dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{notepadpp-light} & notepadpp light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Notion-Dark} & Notion Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Notion-Light} & Notion Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{nova} & nova & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Npm-Dark} & Npm Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Npm-Light} & Npm Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{numpy-dark} & numpy dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{numpy-light} & numpy light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NuxtJS-Dark} & NuxtJS Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{NuxtJS-Light} & NuxtJS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Obsidian-Dark} & Obsidian Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Obsidian-Light} & Obsidian Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{OCaml} & OCaml & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{octane} & octane & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Octave-Dark} & Octave Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Octave-Light} & Octave Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{odin-dark} & odin dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{odin-light} & odin light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ollama-dark} & ollama dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ollama-light} & ollama light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{onedrive-dark} & onedrive dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{onedrive-light} & onedrive light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{onenote-dark} & onenote dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{onenote-light} & onenote light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{OpenAI} & OpenAI & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{OpenCV-Dark} & OpenCV Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{OpenCV-Light} & OpenCV Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{OpenGL} & OpenGL & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{openmm-dark} & openmm dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{openmm-light} & openmm light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{OpenMPI} & OpenMPI & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{OpenShift} & OpenShift & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{opensource-dark} & opensource dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{opensource-light} & opensource light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{OpenStack-Dark} & OpenStack Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{OpenStack-Light} & OpenStack Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{openzeppelin-dark} & openzeppelin dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{openzeppelin-light} & openzeppelin light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{opera-dark} & opera dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{opera-light} & opera light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{oracle-dark} & oracle dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{oracle-light} & oracle light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{orchid} & orchid & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{outlook-dark} & outlook dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{outlook-light} & outlook light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{p5js} & p5js & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{pail-dark} & pail dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{pail-light} & pail light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{pandas-dark} & pandas dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pandas-light} & pandas light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{papertrail} & papertrail & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{payload-dark} & payload dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{payload-light} & payload light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pbi-dark} & pbi dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pbi-light} & pbi light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pennant} & pennant & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Perl} & Perl & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Photoshop} & Photoshop & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{photoshopclassic} & photoshopclassic & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{photoshopexpress} & photoshopexpress & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PHP-Dark} & PHP Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{PHP-Light} & PHP Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{phpstan-dark} & phpstan dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{phpstan-light} & phpstan light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{PhpStorm-Dark} & PhpStorm Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PhpStorm-Light} & PhpStorm Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{picocss-dark} & picocss dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{picocss-light} & picocss light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pinecone-dark} & pinecone dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pinecone-light} & pinecone light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pinescript-dark} & pinescript dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pinescript-light} & pinescript light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Pinia-Dark} & Pinia Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Pinia-Light} & Pinia Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pint} & pint & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Pkl-Dark} & Pkl Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Pkl-Light} & Pkl Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Plan9-Dark} & Plan9 Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Plan9-Light} & Plan9 Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PlanetScale-Dark} & PlanetScale Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PlanetScale-Light} & PlanetScale Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{platformio-dark} & platformio dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{platformio-light} & platformio light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{playwright-dark} & playwright dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{playwright-light} & playwright light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PLines} & PLines & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{plsql-dark} & plsql dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{plsql-light} & plsql light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pm2-dark} & pm2 dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pm2-light} & pm2 light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Pnpm-Dark} & Pnpm Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Pnpm-Light} & Pnpm Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pocketbase-dark} & pocketbase dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pocketbase-light} & pocketbase light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{podman-dark} & podman dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{podman-light} & podman light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{popos} & popos & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{portfolio} & portfolio & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PostgreSQL-Dark} & PostgreSQL Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PostgreSQL-Light} & PostgreSQL Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Postman} & Postman & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PowerBI} & PowerBI & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{powerpoint-dark} & powerpoint dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{powerpoint-light} & powerpoint light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Powershell-Dark} & Powershell Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Powershell-Light} & Powershell Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{preact-dark} & preact dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{preact-light} & preact light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{prelude} & prelude & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Premiere} & Premiere & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{premiererush} & premiererush & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{primevue-dark} & primevue dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{primevue-light} & primevue light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Prisma} & Prisma & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Processing-Dark} & Processing Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Processing-Light} & Processing Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Prometheus} & Prometheus & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{prompts} & prompts & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{proton-dark} & proton dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{proton-light} & proton light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{proxmox-dark} & proxmox dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{proxmox-light} & proxmox light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Pug-Dark} & Pug Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Pug-Light} & Pug Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pulse-dark} & pulse dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pulse-light} & pulse light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Pulumi} & Pulumi & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{puppeteer-dark} & puppeteer dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{puppeteer-light} & puppeteer light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PyCharm-Dark} & PyCharm Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PyCharm-Light} & PyCharm Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pygame-dark} & pygame dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pygame-light} & pygame light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Python-Dark} & Python Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Python-Light} & Python Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PyTorch-Dark} & PyTorch Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{PyTorch-Light} & PyTorch Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pyxel-dark} & pyxel dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{pyxel-light} & pyxel light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{qdrant-dark} & qdrant dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{qdrant-light} & qdrant light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Qemu} & Qemu & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{qodana-dark} & qodana dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{qodana-light} & qodana light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{QT-Dark} & QT Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{QT-Light} & QT Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{R-Dark} & R Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{R-Light} & R Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{RabbitMQ-Dark} & RabbitMQ Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{RabbitMQ-Light} & RabbitMQ Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Rails} & Rails & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{RaspberryPi-Dark} & RaspberryPi Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{RaspberryPi-Light} & RaspberryPi Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{React-Dark} & React Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{React-Light} & React Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{reactbootstrap-dark} & reactbootstrap dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{reactbootstrap-light} & reactbootstrap light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ReactiveX-Dark} & ReactiveX Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ReactiveX-Light} & ReactiveX Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{reactnative-dark} & reactnative dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{reactnative-light} & reactnative light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{reactquery-dark} & reactquery dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{reactquery-light} & reactquery light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{recoil} & recoil & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{RedHat-Dark} & RedHat Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{RedHat-Light} & RedHat Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Redis-Dark} & Redis Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Redis-Light} & Redis Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{redshift-dark} & redshift dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{redshift-light} & redshift light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Redux} & Redux & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Regex-Dark} & Regex Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Regex-Light} & Regex Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Remix-Dark} & Remix Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Remix-Light} & Remix Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{render-dark} & render dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{render-light} & render light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{renpy-dark} & renpy dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{renpy-light} & renpy light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Replit-Dark} & Replit Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Replit-Light} & Replit Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{resharper-dark} & resharper dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{resharper-light} & resharper light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{reverb} & reverb & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{revolt-dark} & revolt dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{revolt-light} & revolt light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Rider-Dark} & Rider Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Rider-Light} & Rider Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{RobloxStudio} & RobloxStudio & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Rocket} & Rocket & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{RollupJS-Dark} & RollupJS Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{RollupJS-Light} & RollupJS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{ROS-Dark} & ROS Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ROS-Light} & ROS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{rubocop-dark} & rubocop dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{rubocop-light} & rubocop light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Ruby} & Ruby & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{rubymine-dark} & rubymine dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{rubymine-light} & rubymine light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{rust-dark} & rust dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{rust-light} & rust light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Rust} & Rust & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{rustrover-dark} & rustrover dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{rustrover-light} & rustrover light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{s3-dark} & s3 dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{s3-light} & s3 light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{safari-dark} & safari dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{safari-light} & safari light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sail} & sail & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{sanctum} & sanctum & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sas-dark} & sas dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{sas-light} & sas light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Sass} & Sass & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Scala-Dark} & Scala Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Scala-Light} & Scala Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{ScikitLearn-Dark} & ScikitLearn Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{SciKitLearn-Light} & SciKitLearn Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{scipy-dark} & scipy dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{scipy-light} & scipy light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{scout} & scout & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{scratch} & scratch & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{seaborn-dark} & seaborn dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{seaborn-light} & seaborn light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Selenium} & Selenium & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Sentry} & Sentry & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Sequelize-Dark} & Sequelize Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Sequelize-Light} & Sequelize Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{sharepoint-dark} & sharepoint dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sharepoint-light} & sharepoint light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{shopify-dark} & shopify dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{shopify-light} & shopify light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{signal} & signal & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{skeletonui-dark} & skeletonui dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{skeletonui-light} & skeletonui light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Sketchup-Dark} & Sketchup Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Sketchup-Light} & Sketchup Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{slack-dark} & slack dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{slack-light} & slack light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{snowflake-dark} & snowflake dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{snowflake-light} & snowflake light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{snyk-dark} & snyk dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{snyk-light} & snyk light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{socialite} & socialite & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{solana-dark} & solana dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{solana-light} & solana light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Solidity} & Solidity & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{SolidJS-Dark} & SolidJS Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{SolidJS-Light} & SolidJS Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sonarqube-dark} & sonarqube dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sonarqube-light} & sonarqube light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{spark-dark} & spark dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{spark-light} & spark light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{SparQL} & SparQL & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Spring-Dark} & Spring Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Spring-Light} & Spring Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Sql} & Sql & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sqlalchemy-dark} & sqlalchemy dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sqlalchemy-light} & sqlalchemy light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{SQLite} & SQLite & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sqlserver-dark} & sqlserver dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{sqlserver-light} & sqlserver light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{StabilityAI} & StabilityAI & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{StackOverflow-Dark} & StackOverflow Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{StackOverflow-Light} & StackOverflow Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{steam} & steam & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{stock} & stock & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{storyblok-dark} & storyblok dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{storyblok-light} & storyblok light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{storybook-dark} & storybook dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{storybook-light} & storybook light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{strapi} & strapi & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{streamlit-dark} & streamlit dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{streamlit-light} & streamlit light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{stripe-dark} & stripe dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{stripe-light} & stripe light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{StyledComponents} & StyledComponents & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{stylus-dark} & stylus dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{stylus-light} & stylus light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Sublime-Dark} & Sublime Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Sublime-Light} & Sublime Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Supabase-Dark} & Supabase Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Supabase-Light} & Supabase Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{surrealdb-dark} & surrealdb dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{surrealdb-light} & surrealdb light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{SuSE} & SuSE & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Svelte} & Svelte & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{SVG-Dark} & SVG Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{SVG-Light} & SVG Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{svn} & svn & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{swagger-dark} & swagger dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{swagger-light} & swagger light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Swift} & Swift & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Symfony-Dark} & Symfony Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Symfony-Light} & Symfony Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{tableau-dark} & tableau dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{tableau-light} & tableau light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{TailwindCSS-Dark} & TailwindCSS Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{TailwindCSS-Light} & TailwindCSS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{tallyprime} & tallyprime & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Tauri-Dark} & Tauri Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Tauri-Light} & Tauri Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{teams-dark} & teams dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{teams-light} & teams light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{telegram} & telegram & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{telescope} & telescope & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{TensorFlow-Dark} & TensorFlow Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{TensorFlow-Light} & TensorFlow Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{terminal-dark} & terminal dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{terminal-light} & terminal light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Terraform-Dark} & Terraform Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Terraform-Light} & Terraform Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{testinglibrary-dark} & testinglibrary dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{testinglibrary-light} & testinglibrary light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ThreeJS-Dark} & ThreeJS Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ThreeJS-Light} & ThreeJS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{thunderbird-dark} & thunderbird dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{thunderbird-light} & thunderbird light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{thunkable} & thunkable & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{tidb-dark} & tidb dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{tidb-light} & tidb light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{tmux-dark} & tmux dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{tmux-light} & tmux light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{tomcat-dark} & tomcat dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{tomcat-light} & tomcat light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{tor-dark} & tor dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{tor-light} & tor light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{trpc} & trpc & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{truffle-dark} & truffle dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{truffle-light} & truffle light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{twig-dark} & twig dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{twig-light} & twig light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{twitch} & twitch & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Twitter} & Twitter & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{typeorm-dark} & typeorm dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{typeorm-light} & typeorm light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{TypeScript} & TypeScript & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Ubuntu-Dark} & Ubuntu Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Ubuntu-Light} & Ubuntu Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{ubuntu} & ubuntu & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Ultralytics} & Ultralytics & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Unity-Dark} & Unity Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Unity-Light} & Unity Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{unitycatalog-dark} & unitycatalog dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{unitycatalog-light} & unitycatalog light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{unocss-dark} & unocss dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{unocss-light} & unocss light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{UnrealEngine} & UnrealEngine & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{V-Dark} & V Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{V-Light} & V Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{vagrant-dark} & vagrant dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{vagrant-light} & vagrant light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Vala} & Vala & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{vapor} & vapor & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Vercel-Dark} & Vercel Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Vercel-Light} & Vercel Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VIM-Dark} & VIM Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VIM-Light} & VIM Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{virtualbox-dark} & virtualbox dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{virtualbox-light} & virtualbox light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{visualbasic-dark} & visualbasic dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{visualbasic-light} & visualbasic light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VisualStudio-Dark} & VisualStudio Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VisualStudio-Light} & VisualStudio Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Vite-Dark} & Vite Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Vite-Light} & Vite Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Vitest-Dark} & Vitest Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Vitest-Light} & Vitest Light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{vmwareworkstation-dark} & vmwareworkstation dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{vmwareworkstation-light} & vmwareworkstation light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{VSCode-Dark} & VSCode Dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VSCode-Light} & VSCode Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VSCodium-Dark} & VSCodium Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VSCodium-Light} & VSCodium Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{VueJS-Dark} & VueJS Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{VueJS-Light} & VueJS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Vuetify-Dark} & Vuetify Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Vuetify-Light} & Vuetify Light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Vulkan} & Vulkan & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{vyper-dark} & vyper dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{vyper-light} & vyper light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{wails-dark} & wails dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{wails-light} & wails light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{wandb-dark} & wandb dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{wandb-light} & wandb light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Wasm} & Wasm & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{WebAssembly} & WebAssembly & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Webflow} & Webflow & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Webpack-Dark} & Webpack Dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Webpack-Light} & Webpack Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{WebStorm-Dark} & WebStorm Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{WebStorm-Light} & WebStorm Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{wezterm-dark} & wezterm dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{wezterm-light} & wezterm light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{WindiCSS-Dark} & WindiCSS Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{WindiCSS-Light} & WindiCSS Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Windows-Dark} & Windows Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Windows-Light} & Windows Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{wireshark-dark} & wireshark dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{wireshark-light} & wireshark light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{word-dark} & word dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{word-light} & word light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Wordpress} & Wordpress & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Workers-Dark} & Workers Dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Workers-Light} & Workers Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{wsl-dark} & wsl dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{wsl-light} & wsl light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{x-dark} & x dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{x-light} & x light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{xcode-dark} & xcode dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{xcode-light} & xcode light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{XD} & XD & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{yaml-dark} & yaml dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{yaml-light} & yaml light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{yammer-dark} & yammer dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{yammer-light} & yammer light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Yarn-Dark} & Yarn Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Yarn-Light} & Yarn Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Yew-Dark} & Yew Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Yew-Light} & Yew Light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{yii-dark} & yii dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{yii-light} & yii light & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{Yocto} & Yocto & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{youtube} & youtube & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zabbix} & zabbix & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zed-dark} & zed dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zed-light} & zed light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{zellij-dark} & zellij dark & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zellij-light} & zellij light & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zen-dark} & zen dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zen-light} & zen light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Zig-Dark} & Zig Dark & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{Zig-Light} & Zig Light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
\photosymbol{zudoku-dark} & zudoku dark & 3 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zudoku-light} & zudoku light & 2 & \textcolor{lightgray}{$\bullet$} & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zustand-dark} & zustand dark & 1 & $\bullet$ & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} \\ 
\photosymbol{zustand-light} & zustand light & 4 & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & \textcolor{lightgray}{$\bullet$} & $\bullet$ \\ 
%
% found #1011 images

